# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d3a4d64957344adec58d38a83d63ba5f7d5e037bde56157bca12756e632668450c6a62e9018784b0f337728af02db9bc1a7c895b1ba194ea77c4bdebfb6873

test:
  secret_key_base: 8905f95edb8efc159e740580f42cb2f7f6536db35d6e68fe2389dd1924394268a76231b1be43d26001afc6976b6e633d83a3a6abbdcc90834888a075a1df77b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
